### ISSUE TITLE
"add timer" component

### ISSUE THREAD

**Issue by kpalatzky** [self-sample/angular-timer#1]
To create a new timer a new component must be created. In this component it should be possible to select the date and time of the timer with a Datetime Picker and to set a description for it. The timer should then be added to the Timer Service

**Comment by A-Annan** [comment]
Could assign it to me

**Comment by kpalatzky** [comment]
@A-Annan Thanks for your help!

**Comment by A-Annan** [comment]
when I add a new timer the timerDuration$ is not set 
![image](https://user-images.githubusercontent.com/23015439/96353603-7f94ec00-10c5-11eb-8d96-c1cce4303c82.png)
also when I refresh I found that a new timer was automatically added !

**Comment by kpalatzky** [comment]
@A-Annan You have to call addTimer in the timerService. 

The timer that is created at refresh is just for debugging - You can remove the „startWith“ inside the timer.service.

If you can finish the UI/Component for creating a timer i can integrate it myself.
