### ISSUE TITLE
Better display for duration

### ISSUE THREAD

**Issue by kpalatzky** [self-sample/angular-timer#2]
Currently the duration is only displayed as ms timestamp. This should be displayed as a better value using a pipe as days / hours / minutes (3d 5h 23m). If the timer is less than one hour, the seconds should also be displayed (59:43m or 49m 23s).

**Comment by alexhoffman617** [comment]
I can take this on if you want to assign it to me.

**Comment by kpalatzky** [comment]
@alexhoffman617 Have fun!

**Comment by kpalatzky** [comment]
@alexhoffman617 Thanks for your help!
